name: DEV - ZAP Scan
on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency: ci-${github.ref}-dev
    environment:
      name: dev

    steps:
      - name: Wait for a minute after deployment is completed
        run: sleep 60
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: https://dev.tbcm.freshworks.club/
          issue_title: DEV - ZAP Full Scan Report
          cmd_options: '-I'
          rules_file_name: '.zap/rules.tsv'
