name: PROD - ZAP Scan
on:
  workflow_dispatch:
  schedule:
    # Runs every month on 1st at 01:00
    - cron: '0 1 1 * *'

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency: ci-${github.ref}-prod
    environment:
      name: prod

    steps:
      - name: Wait for a minute after deployment is completed
        run: sleep 60
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: https://moc.gov.bc.ca/
          issue_title: PROD - ZAP Full Scan Report
          cmd_options: '-I'
          rules_file_name: '.zap/rules.tsv'
